### ISSUE TITLE
Implement Inference in PyTorch

### ISSUE THREAD

**Issue by tpankaj** [sauhaardac/pytorch-neural-z2color#13]
Figure out how to convert any of the weights files to a caffemodel that we can use to run the network in Caffe.

**Comment by raunakdoesdev** [comment]
Posted to PyTorch Forums to see if there is an existing solution:
https://discuss.pytorch.org/t/converted-trained-pytorch-model-to-caffe/1384

**Comment by tpankaj** [comment]
Looks like no such conversion tool exists.

**Comment by raunakdoesdev** [comment]
Need to find implementation of inference in Caffe and migrate to pytorch model.

**Comment by raunakdoesdev** [comment]
This is being implemented in a separate GitHub repository:
https://github.com/sauhaardac/pytorch_inference
Please file any inference issues there in the future.
