### ISSUE TITLE
Implement data preloading

### ISSUE THREAD

**Issue by tpankaj** [sauhaardac/pytorch-neural-z2color#14]
Preload data onto the GPUs ahead of time during training to minimize overhead of SSD/CPU accesses.

**Comment by raunakdoesdev** [comment]
Had a talk with Karl, and apparently they implemented this a while back with the Caffe when they were trying to load the data and it didn't have a measurable affect on performance and just took up more GPU space. I don't know if this will be worth the effort so I'm marking this as wontfix.
